### PR TITLE
Add cross join to list of keywords

### PR DESCRIPTION
**Pull request by Jedi18**
sql_metadata fails to detect some tables in queries containing CROSS JOIN. Added CROSSJOIN to the list of keywords.

### CODE REVIEW

**Comment by collerek** [comment]
Great, thanks!
Can you add one more test with cross join to subquery and some checks for both columns and tables?

**Comment by Jedi18** [comment]
Ok added a few more, are these the tests you were referring to or did I miss something?

**Comment by macbre** [comment]
@Jedi18 , thanks for these tests. Please make sure that they pass:

```
=========================== short test summary info ============================
FAILED test/test_getting_columns.py::test_joins - AttributeError: 'NoneType' ...
FAILED test/test_getting_tables.py::test_cross_join_with_subquery - Assertion...
======================== 2 failed, 130 passed in 2.73s =========================
```

**Comment by Jedi18** [comment]
@macbre Sorry, should've tested it locally instead of relying on the CI. They should pass now.

**Review by macbre — APPROVED** [review]

**Pull request merged**
