### PR TITLE
Add `USING` to column keywords

### PR DESCRIPTION
**Pull request by glentakahashi**
https://www.geeksforgeeks.org/sql-using-clause/
https://docs.oracle.com/javadb/10.6.2.1/ref/rrefsqljusing.html

UPDATE: Also fixed to specifically not count `USING` when doing `CONVERT(somecol USING utf8)`

### CODE REVIEW

**Comment by collerek** [comment]
Thank you for your contribution! :)

We do have a test for convert using already but note that converts can happen not only in select.
In example this test should pass too (and it does on the current master):

```python
def test_convert_in_join():
    parser = Parser("SELECT la1.col1, la2.col2 FROM latin1_table la1 "
                    "left join latin2_table la2 "
                    "on CONVERT(la1.latin1_column USING utf8) ="
                    " CONVERT(la2.latin1_column USING utf8)"
                    ";")
    assert parser.columns == [
        'latin1_table.col1',
        'latin2_table.col2',
        'latin1_table.latin1_column',
        'latin2_table.latin1_column']
    assert parser.columns_dict == {
        'join': ['latin1_table.latin1_column', 'latin2_table.latin1_column'],
        'select': ['latin1_table.col1', 'latin2_table.col2']}
    assert parser.tables == ['latin1_table', 'latin2_table']
```

Note how excluding `using` from relevant keywords based on preceding `select` will not work, you probably have to heck for nth previous to find `CONVERT` in the normalized value.

Note also, that your change adds `using` to `columns_dict` keys, which is wrong (`using` clause still happens in a `join` (instead of `on`) and that's where the columns should go in the `columns_dict`). In theory, those columns should be duplicated with a prefix of each table (as using takes columns with same names from both tables).

**Comment by glentakahashi** [comment]
Hmm @collerek I added that test and it passes too? TBH I had a hard time following /all/ the logic around potential column resolution, so defer to your guidance here, but it looks like it still works even in that case.

**Comment by glentakahashi** [comment]
hi @collerek @macbre just wanted to check if you have any other thoughts on this PR

**Comment by collerek** [comment]
Sorry for the late answer!

OK, I was trying to avoid adding `USING` to column keywords at all, but at the same time I cannot think of a valid SQL that would break your implementation so it seems it's good to go :)

Can you fix the hanging space listed in CodeFactor? (I know it's not related to your work, just to clean it up) :)

**Comment by glentakahashi** [comment]
@collerek all fixed up!

**Review by collerek — APPROVED** [review]

**Comment by collerek** [comment]
@macbre LGTM, ready to merge.

**Pull request merged**
