### PR TITLE
get_query_table_aliases(query) is far from being final

### LINKED ISSUE #97: get_query_table_aliases(query) is far from being final
While I was testing on Oracle SQL:

- missed LEFT JOINs (it was easy to add to the code)
- missed table names starting with schema name (SCHEMA.TABLE)
- missed aliases without AS (this is mentioned in the code but not handled)
- missed recognizing subselects (e.g. FROM (SELECT ... ) )

I touched the code to overcome these issues and found solution for them. Tested with a huge SQL but may need to do some more testing.

New code:

```python
def get_query_table_aliases(query: str) -> Dict[str, str]:
    """
    Returns tables aliases mapping from a given query

    E.g. SELECT a.* FROM users1 AS a JOIN users2 AS b ON a.ip_address = b.ip_address
    will give you {'a': 'users1', 'b': 'users2'}
    """
    aliases = dict()
    last_keyword_token = None
    last_table_name = None

    for token in get_query_tokens(query):
        # print(token.ttype, token, last_table_name)

        # handle "FROM foo alias" syntax (i.e, "AS" keyword is missing)
        # if last_table_name and token.ttype is Name:
        #     aliases[token.value] = last_table_name
        #     last_table_name = False

        if last_table_name:
            if token.value=='.': 
                last_table_name = last_table_name + token.value #add the dot
            if token.value==',' or token.is_keyword and token.value.upper()!='AS': #there is no alias
                aliases[''] = last_table_name
                last_table_name = False
            if prev_token.value.upper()=='AS': #previous keyword was AS then we found the alias
                aliases[token.value] = last_table_name
                last_table_name = False
            if token.ttype is Name: 
                if prev_token.value=='.': 
                    last_table_name = last_table_name + token.value #add Name to last_table_name
                else: #found alias
                    aliases[token.value] = last_table_name
                    last_table_name = False


        if last_keyword_token:
           if last_keyword_token.value.upper() in ["FROM", "JOIN", "INNER JOIN","LEFT JOIN"] and token.value!='(':
                last_table_name = token.value

        last_keyword_token = token if token.is_keyword else False
        prev_token = token

    return aliases

### PR DESCRIPTION
**Pull request by macbre**
Fixes #97

### CODE REVIEW

**Comment by macbre** [comment]
@bandrisca - please follow `pylint` suggestions and reformat the code with `black`.

**Comment by bandrisca** [comment]
> 
> 
> @bandrisca - please follow `pylint` suggestions and reformat the code with `black`.

@macbre sorry, I do not know how to do that. Can you please format it for me or tell me how can I do it?

**Comment by macbre** [comment]
@bandrisca: no worries 🙂 In order to reformat the code simply run the following:

```
pip install black
black .
```

And commit the changes made by the `black` tool.

**Comment by bandrisca** [comment]
> 
> 
> @bandrisca: no worries 🙂 In order to reformat the code simply run the following:
> 
> ```
> pip install black
> black .
> ```
> 
> And commit the changes made by the `black` tool.
> 
> As for the `pylint` errors - these places need some changes:
> 
> ```
> ************* Module sql_metadata
> sql_metadata.py:381:32: C0303: Trailing whitespace (trailing-whitespace)
> sql_metadata.py:383:0: C0301: Line too long (101/100) (line-too-long)
> sql_metadata.py:389:35: C0303: Trailing whitespace (trailing-whitespace)
> sql_metadata.py:390:41: C0303: Trailing whitespace (trailing-whitespace)
> sql_metadata.py:397:0: C0301: Line too long (114/100) (line-too-long)
> sql_metadata.py:397:0: W0311: Bad indentation. Found 11 spaces, expected 12 (bad-indentation)
> sql_metadata.py:402:0: C0303: Trailing whitespace (trailing-whitespace)
> ```

I istalled "black" and it successfully reformatted the code, but still I see the length of the lines are more than 100 chars.
Do I have to modify them manually?
Did "black" remove unwanted whitespaces and bad indentations?
I compared the original and the reformatted code but found no change.
Is there a predifined black setup for github?

**Comment by macbre** [comment]
Please commit the changes made by `black` and we'll see what needs to be updated.

**Comment by bandrisca** [comment]
hi @macbre , I am not sure about what I am doing, but finally I managed to upload the formatted code. Is it ok now, or too late?

**Comment by macbre** [comment]
@bandrisca - still no improvement. Check the outputs of the checks listed below. Additionally, unit tests do not pass for the updated functions.

**Comment by macbre** [comment]
`black` passes now 🎉

**Comment by macbre** [comment]
@bandrisca  - do you need any help with this one?

**Comment by macbre** [comment]
@bandrisca - #121 introduced a completely new SQL parser and new API. Closing this in favour of #121.

**Pull request closed without merging**
